### PR TITLE
Add check for undocumented names; remove a dangling exported function

### PR DESCRIPTION
**Pull request by pjaap**

### CODE REVIEW

**Comment by pjaap** [comment]
I'll fix the documentation problem

**Comment by pjaap** [comment]
Hmm, CI complaines that ` GridVisualize.GridVisualize` is not in the docs. That is true. But I wanted to use the README as documentation for this. Where do I put this in the docs?

**Comment by jpthiele** [comment]
We could do an `allindex.md` similar to how VoronoiFVM does it https://wias-pdelib.github.io/VoronoiFVM.jl/stable/allindex/
inside the `public api` part of docs.

**Comment by j-fu** [comment]
I always would put the module doc on top of docs/src/index.md

**Comment by jpthiele** [comment]
I solved it in GridVisualizeTools like this https://github.com/WIAS-PDELib/GridVisualizeTools.jl/pull/18/commits/d94e6327966140b182bcf763f12a764168729d0c

@j-fu, did you check the resulting docs to see if you like how the result looks?

**Comment by j-fu** [comment]
I checked the docs locally, it works.

**Comment by jpthiele** [comment]
Good. 
Can we remove the unrelated formatting commit from this PR? or move it to #57 ?

**Comment by j-fu** [comment]
this is just the pluto notebook thing. I think it is not worth to bother that much about this. I would just keep it here, if you want to move it, it's ok as well.

**Comment by jpthiele** [comment]
I have removed the unrelated change to `examples/plutovista.jl` from 'update index.md' and with it the wrong format introduced therein.

**Comment by pjaap** [comment]
Should be good now

**Pull request merged**
