### PR TITLE
Bump version and add myself to list of authors

### PR DESCRIPTION
**Pull request by pjaap**

### CODE REVIEW

**Comment by pjaap** [comment]
@j-fu just to make sure (my first version bump). I added myself to the authors and after merge I simply comment the commit with the Julia registrator?

**Comment by j-fu** [comment]
Yes, "@JuliaRegistrator register" should be sufficient to trigger everything.
As for the invalidation action: I think we can remove it at the moment, as
others do, see

https://github.com/julia-actions/julia-invalidations/issues/19

**Comment by j-fu** [comment]
> Comments on pull requests will not trigger Registrator, as it is disabled. Please try commenting on a commit or issue.

Ah it seems the registrator got triggered here :) Good he know his place.

**Comment by pjaap** [comment]
Oops, a false positive trigger :)

**Comment by pjaap** [comment]
I started the registration on the merged commit.

**Pull request merged**
